### PR TITLE
[PKG-3484] weasel 0.3.4

### PR DESCRIPTION
**Pull request by lorepirri**
weasel 0.3.4

**Destination channel:** defaults

### Links

- [PKG-3484]
- https://github.com/explosion/weasel/tree/v0.3.4

**Depends on:**

- AnacondaRecipes/cloudpathlib-feedstock#3

[PKG-3484]: https://anaconda.atlassian.net/browse/PKG-3484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]

**Comment by skupr-anaconda** [comment]
The fix for `.gitmodules` https://github.com/AnacondaRecipes/weasel-feedstock/pull/1

**Review by psteyer — APPROVED** [review]
LGTM

**Comment by skupr-anaconda** [comment]
logs:
`INFO   Running command: git clone -b 3.12 --depth 1 git@github.com:AnacondaRecipes/aggregate.git "/tmp/abs_15739res_j/clone/.abs"`

https://github.com/AnacondaRecipes/aggregate/blob/3.12/.gitmodules hasn't had a change in a while....

**Comment by skupr-anaconda** [comment]
Trying to add the submodule to the branch `3.12` https://github.com/AnacondaRecipes/aggregate/pull/306

**Comment by lorepirri** [comment]
`cloudpathlib` is missing for `py312`

```
for p in linux-{64,s390x,aarch64} win-64 osx-{64,arm64}; do echo -e "*** $p"; conda search -q --platform=$p "cloudpathlib>=0.7.0,<0.17.0" -c main --override-channels; echo ""; done
*** linux-64
Loading channels: ...working... done
# Name                       Version           Build  Channel
cloudpathlib                  0.16.0 py310h06a4308_0  main
cloudpathlib                  0.16.0 py311h06a4308_0  main
cloudpathlib                  0.16.0  py38h06a4308_0  main
cloudpathlib                  0.16.0  py39h06a4308_0  main

*** linux-s390x
Loading channels: ...working... done
# Name                       Version           Build  Channel
cloudpathlib                  0.16.0 py310ha847dfd_0  main
cloudpathlib                  0.16.0 py311ha847dfd_0  main
cloudpathlib                  0.16.0  py38ha847dfd_0  main
cloudpathlib                  0.16.0  py39ha847dfd_0  main

*** linux-aarch64
Loading channels: ...working... done
# Name                       Version           Build  Channel
cloudpathlib                  0.16.0 py310hd43f75c_0  main
cloudpathlib                  0.16.0 py311hd43f75c_0  main
cloudpathlib                  0.16.0  py38hd43f75c_0  main
cloudpathlib                  0.16.0  py39hd43f75c_0  main

*** win-64
Loading channels: ...working... done
# Name                       Version           Build  Channel
cloudpathlib                  0.16.0 py310haa95532_0  main
cloudpathlib                  0.16.0 py311haa95532_0  main
cloudpathlib                  0.16.0  py38haa95532_0  main
cloudpathlib                  0.16.0  py39haa95532_0  main

*** osx-64
Loading channels: ...working... done
# Name                       Version           Build  Channel
cloudpathlib                  0.16.0 py310hecd8cb5_0  main
cloudpathlib                  0.16.0 py311hecd8cb5_0  main
cloudpathlib                  0.16.0  py38hecd8cb5_0  main
cloudpathlib                  0.16.0  py39hecd8cb5_0  main

*** osx-arm64
Loading channels: ...working... done
# Name                       Version           Build  Channel
cloudpathlib                  0.16.0 py310hca03da5_0  main
cloudpathlib                  0.16.0 py311hca03da5_0  main
cloudpathlib                  0.16.0  py38hca03da5_0  main
cloudpathlib                  0.16.0  py39hca03da5_0  main
```

**Comment by skupr-anaconda** [comment]
@lorepirri `cloudpathlib 0.16.0` with **py312** support  https://github.com/AnacondaRecipes/cloudpathlib-feedstock/pull/3

**Comment by skupr-anaconda** [comment]
> `cloudpathlib 0.16.0` with **py312** support [AnacondaRecipes/cloudpathlib-feedstock#3](https://github.com/AnacondaRecipes/cloudpathlib-feedstock/pull/3)

`cloudpathlib 0.16.0` already has the **py312** support

**Comment by skupr-anaconda** [comment]
@lorepirri It's already unblocked

**Comment by lorepirri** [comment]
> @lorepirri It's already unblocked

thank you very much @skupr-anaconda , I will merge this and after `spacy`

**Pull request merged**
